name: Pull request handler

on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  process-new-pr:
    name: Handle new pull request
    runs-on:
      group: Default Larger Runners
      labels: ubuntu-latest-m
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Assign pull request reviewers
        uses: ./.github/.release/actions/actions/utils/assign-reviewers
        with:
          token: ${{ secrets.GH_TOKEN }}
