name: Test

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: React e2e tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/android_ios/testing_apps/android
    strategy:
      fail-fast: true
      matrix:
        app: ["Getting started"]
    steps:
      - name: Setup NodeJS 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Checkout e2e repository
        uses: actions/checkout@v3
        with:
          repository: pubnub/chat-components-e2e-tests
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: android_ios/chat-components-android
      - name: Install e2e framework dependencies
        run: npm ci
      - name: Build ${{ matrix.app }} application
        run: echo "::notice title=Demo application::Using pre-build ${{ matrix.app }}. Please think about building it during test run."
      - name: Install and run Appium
        run: |
          npm install -g appium
          appium &
      - name: Update Java paths
        run: |
          echo "$JAVA_HOME_17_X64" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
      - name: Android paths
        run: |
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          ls -la "$ANDROID_SDK_ROOT"
          echo "Files in $ANDROID_SDK_ROOT/platform-tools:"
          ls -la "$ANDROID_SDK_ROOT/platform-tools"
          echo "Files in $ANDROID_SDK_ROOT/emulator:"
          ls -la "$ANDROID_SDK_ROOT/emulator"
          echo "Adb devices:"
          $ANDROID_SDK_ROOT/platform-tools/adb devices
          echo "1 >> List AVDs:"
          $ANDROID_SDK_ROOT/emulator/emulator -list-avds
          echo "Creating avd"
          [[ $RUNNER_ARCH == X86 ]] && ARCH=x86 || ARCH=x86_64
          TARGET=google_apis
          API_LEVEL=30
          DEVICE="Pixel 2"
          AVD_IMAGE_NAME="$(echo "$DEVICE" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')_API_$API_LEVEL"
          echo "COMMAND: echo no | $ANDROID_SDK_ROOT/tools/bin/avdmanager create avd --verbose --force --name \"$AVD_IMAGE_NAME\" --abi \"$TARGET/$ARCH\" --package \"system-images;android-$SDK_VERSION;$TARGET;$ARCH\" --device \"$DEVICE\""
          echo no | $ANDROID_SDK_ROOT/tools/bin/avdmanager create avd --verbose --force --name "$AVD_IMAGE_NAME" --abi "$TARGET/$ARCH" --package "system-images;android-$SDK_VERSION;$TARGET;$ARCH" --device "$DEVICE"
          echo "2 >> Adb devices:"
          $ANDROID_SDK_ROOT/tools/adb devices
      - name: List Android simulators
        run: adb devices
      - name: Run e2e tests for ${{ matrix.app }}
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          npm run androidlocal
