name: Test

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: React e2e tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/android_ios/testing_apps/android
    strategy:
      fail-fast: true
      matrix:
        app: ["Getting started"]
    steps:
      - name: Setup NodeJS 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Checkout e2e repository
        uses: actions/checkout@v3
        with:
          repository: pubnub/chat-components-e2e-tests
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: android_ios/chat-components-android
      - name: Install e2e framework dependencies
        run: npm ci
      - name: Build ${{ matrix.app }} application
        run: echo "::notice title=Demo application::Using pre-build ${{ matrix.app }}. Please think about building it during test run."
      - name: Install and run Appium
        run: |
          npm install -g appium
          appium &
      - name: Update Java paths
        run: |
          echo "$JAVA_HOME_17_X64" >> $GITHUB_PATH
          echo "$ANDROID_HOME/cmdline-tools" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
      - name: Accept Android licenses
        run: |
          ls -la "$ANDROID_HOME/cmdline-tools"
          sudo chown $USER:$USER $ANDROID_HOME -R
          yes | sdkmanager --licenses > /dev/null
      - name: List existing devices
        run: adb devices
      - name: List existing AVDs
        run: emulator -list-avds
      - name: Create suitable AVD
        run: |
          [[ $RUNNER_ARCH == X86 ]] && ARCH=x86 || ARCH=x86_64
          API_LEVEL=30
          TARGET=google_apis
          DEVICE="Pixel"
          sdkmanager --install 'build-tools;$API_LEVEL.0.0' platform-tools 'platforms;android-$API_LEVEL' > /dev/null
          sdkmanager --install emulator --channel=0 > /dev/null
          sdkmanager --install 'system-images;android-$API_LEVEL;$TARGET;$ARCH' --channel=0 > /dev/null
          echo no | avdmanager create avd --force -n test --abi "'$TARGET/$API_LEVEL'" --package "'system-images;android-$API_LEVEL;$TARGET;$API_LEVEL'" --device "'$DEVICE'"
          echo 'hw.cpu.ncore=2' >> /home/runner/.android/avd/test.avd/config.ini
      - name: List existing AVDs
        run: emulator -list-avds
      - name: Launch emulator
        run: |
          echo "Starting emulator and waiting for boot to complete..."
          emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -accel off &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do echo "Not ready" && sleep 1; done; input keyevent 82'
      - name: List existing devices
        run: |
          echo "Emulator has finished booting"
          adb devices
      - name: Run e2e tests for ${{ matrix.app }}
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          npm run androidlocal
