name: Test

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: React e2e tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/android_ios/testing_apps/android
    strategy:
      fail-fast: true
      matrix:
        app: ["Getting started"]
    steps:
      - name: Setup NodeJS 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Checkout e2e repository
        uses: actions/checkout@v3
        with:
          repository: pubnub/chat-components-e2e-tests
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: android_ios/chat-components-android
      - name: Install e2e framework dependencies
        run: npm ci
      - name: Build ${{ matrix.app }} application
        run: echo "::notice title=Demo application::Using pre-build ${{ matrix.app }}. Please think about building it during test run."
      - name: Install and run Appium
        run: |
          npm install -g appium
          appium &
      - name: Update Java paths
        run: |
          echo "JAVA 17 PATH: $JAVA_HOME_17_X64"
          echo "$JAVA_HOME_17_X64" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
          echo "PATHS: $(cat $GITHUB_PATH)"
          echo "ENVS: $(cat $GITHUB_ENV)"
      - name: Run e2e tests for ${{ matrix.app }}
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          npm run androidlocal
